name: silent_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  google_maps_flutter: ^2.12.1
  location: ^8.0.0
  speech_to_text: ^7.0.0
  flutter_local_notifications: ^19.0.0
  sqflite: ^2.4.2
  provider: ^6.1.4
  font_awesome_flutter: ^10.8.0
  flutter_background_service: ^5.1.0
  flutter_background: ^1.3.0+1
  shared_preferences: ^2.5.3
  mailer: ^6.4.1
  flutter_launcher_icons: ^0.14.3
  #flutter_sms: ^2.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter_icons:
  android: true
  image_path: "assets/flutter.png"
flutter:
  uses-material-design: true
